### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by primepake** [XChenZ/havatar#3]
Traceback (most recent call last):
  File "/home/codes/havatar/avatarHD_reenactment.py", line 6, in <module>
    from model.nerf_trainer import Trainer as nerf_trainer
  File "/home/codes/havatar/model/nerf_trainer.py", line 3, in <module>
    from model import nerf_model
  File "/home/codes/havatar/model/nerf_model.py", line 3, in <module>
    from utils.sh_util import eval_sh
ModuleNotFoundError: No module named 'utils'

**Comment by XChenZ** [comment]
Sorry, it's a mistake that we forgot some files. The folder `utils` has been uploaded.

**Comment by primepake** [comment]
Thanks

**Comment by primepake** [comment]
another issue
avatarHD_reenactment.py: error: unrecognized arguments: --torch_test

**Comment by XChenZ** [comment]
Just remove the argument --torch_test. We have updated the ReadMe.
