### ISSUE TITLE
How to install the upfirdn2d module?

### ISSUE THREAD

**Issue by ASAmbitious** [XChenZ/havatar#5]
pip install upfirdn2d
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement upfirdn2d (from versions: none)
ERROR: No matching distribution found for upfirdn2d
The installation has been unsuccessful, does anyone know the reason? How to solve it?

**Comment by ASAmbitious** [comment]
Traceback (most recent call last):
  File "train_avatarHD.py", line 19, in <module>
    from model.nerf_trainer import Trainer
  File "/home/su2204/code/havatar-main/model/nerf_trainer.py", line 3, in <module>
    from model import nerf_model
  File "/home/su2204/code/havatar-main/model/nerf_model.py", line 6, in <module>
    from model.styleUnet import StyleGAN_zxc, StyleGAN_zxc_twoHead
  File "/home/su2204/code/havatar-main/model/styleUnet.py", line 7, in <module>
    from model.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "/home/su2204/code/havatar-main/model/op/__init__.py", line 2, in <module>
    from .upfirdn2d import upfirdn2d
  File "/home/su2204/code/havatar-main/model/op/upfirdn2d.py", line 19, in <module>
    import upfirdn2d as upfirdn2d_op
ModuleNotFoundError: No module named 'upfirdn2d'
This is the complete question。

**Comment by XChenZ** [comment]
You need to compile the ops provided by [stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch) using ninja:
cd model/op
python setup.py install

**Comment by ASAmbitious** [comment]
(havatar) su2204@PC2212037:~/code/havatar-main$ python avatarHD_reenactment.py --savedir results/demo/self-recon --ckpt logs/demo/HD/latest.pt --split data/demo/sv_v31_all.json
logs/demo/HD/latest.pt
StyleGAN conditon img!
StyleGAN conditon img!
/home/su2204/miniconda3/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                                                         | 0/3053 [00:00<?, ?it/s]
[ WARN:0@9.865] global loadsave.cpp:248 findDecoder imread_('/media/zxc/hdd2/Dataset/MV-video/singleView/test_wlz0318/video_track_singleView_v31/30/ortho_front_normal_256_baseGama.png'): can't open/read file: check file path/integrity
  0%|                                                                                                                                                                         | 0/3053 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/su2204/code/havatar-main/avatarHD_reenactment.py", line 176, in <module>
    main()
  File "/home/su2204/code/havatar-main/avatarHD_reenactment.py", line 152, in main
    for idx, val_batch in tqdm(val_loader):
  File "/home/su2204/miniconda3/lib/python3.11/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/su2204/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/su2204/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su2204/miniconda3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su2204/miniconda3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/su2204/code/havatar-main/dataloader/dataloaderSR.py", line 73, in __getitem__
    data_dict = self.load_data(frame_dict)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su2204/code/havatar-main/dataloader/dataloaderSR.py", line 145, in load_data
    data_dict['front_render_cond'] = make_render_cond_(normal_path=os.path.join(frame_dict['inst_dir'], 'ortho_front_normal_256_baseGama.png'),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/su2204/code/havatar-main/dataloader/dataloaderSR.py", line 160, in make_render_cond_
    normal = cv2.cvtColor(cv2.imread(normal_path), cv2.COLOR_BGR2RGB)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
data/demo/sv_v31_all.json file, an OpenCV error message appeared, indicating that there was a problem reading the file /media/zxc/hdd2/Dataset/MV-video/singleView/test_wlz0318/video_track_singleView_v31/30/ortho_front_normal_256_baseGama.png .
Can we generate this json file ourselves? ortho_front_normal_256_baseGama.png What is the form of this picture?
Looking forward to your answers

**Comment by XChenZ** [comment]
'sv_v31_all.json' can be generated by data_preprocessing/fit_video.py, if you try to prepare your own dataset.
To directly utilize the demo dataset, you can change the full path prefix `/media/zxc/hdd2/Dataset/MV-video/singleView/test_wlz0318` to the demo data path in your machine.
`ortho_front_normal_256_baseGama.png` is 3DMM rendering result, which can be generated by data_preprocessing/fit_video.py
